# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bess_lm <- function(X, y, T, max_steps, beta0) {
    .Call('BeSS_bess_lm', PACKAGE = 'BeSS', X, y, T, max_steps, beta0)
}

get_A <- function(X, y, beta, coef0, T, B) {
    .Call('BeSS_get_A', PACKAGE = 'BeSS', X, y, beta, coef0, T, B)
}

get_A2 <- function(X, y, beta, coef0, max_T, B) {
    .Call('BeSS_get_A2', PACKAGE = 'BeSS', X, y, beta, coef0, max_T, B)
}

getcox_A <- function(X, y, beta, T, B, status) {
    .Call('BeSS_getcox_A', PACKAGE = 'BeSS', X, y, beta, T, B, status)
}

getcox_A2 <- function(X, y, beta, max_T, B, status) {
    .Call('BeSS_getcox_A2', PACKAGE = 'BeSS', X, y, beta, max_T, B, status)
}

abess_lm <- function(X, y, T0L, T0R, K_max, max_steps, beta0, eps) {
    .Call('BeSS_abess_lm', PACKAGE = 'BeSS', X, y, T0L, T0R, K_max, max_steps, beta0, eps)
}

