# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bess_cox <- function(X, status, T0, max_steps, beta, weights, cox_max = 10L, eta = 0.5, normal = TRUE) {
    .Call(`_BeSS_bess_cox`, X, status, T0, max_steps, beta, weights, cox_max, eta, normal)
}

bess_coxs <- function(X, status, T_list, max_steps, beta0, weights, warm_start = FALSE, cox_max = 20L, eta = 0.2, normal = TRUE) {
    .Call(`_BeSS_bess_coxs`, X, status, T_list, max_steps, beta0, weights, warm_start, cox_max, eta, normal)
}

bess_cox_gs <- function(X, status, s_min, s_max, K_max, max_steps, epsilon, beta0, weights, warm_start = FALSE, cox_max = 20L, eta = 0.2, normal = TRUE) {
    .Call(`_BeSS_bess_cox_gs`, X, status, s_min, s_max, K_max, max_steps, epsilon, beta0, weights, warm_start, cox_max, eta, normal)
}

ggetcox_A <- function(X, G, index, T0, beta0, n, p, N, status, weights, B00) {
    .Call(`_BeSS_ggetcox_A`, X, G, index, T0, beta0, n, p, N, status, weights, B00)
}

bess_glm <- function(X, y, T0, max_steps, beta, coef0, weights, glm_max = 20L, normal = TRUE) {
    .Call(`_BeSS_bess_glm`, X, y, T0, max_steps, beta, coef0, weights, glm_max, normal)
}

bess_glms <- function(X, y, T_list, max_steps, beta0, intercept, weights, warm_start = FALSE, glm_max = 20L, normal = TRUE) {
    .Call(`_BeSS_bess_glms`, X, y, T_list, max_steps, beta0, intercept, weights, warm_start, glm_max, normal)
}

bess_glm_gs <- function(X, y, s_min, s_max, K_max, max_steps, epsilon, beta0, coef0, weights, warm_start = FALSE, normal = TRUE, glm_max = 20L) {
    .Call(`_BeSS_bess_glm_gs`, X, y, s_min, s_max, K_max, max_steps, epsilon, beta0, coef0, weights, warm_start, normal, glm_max)
}

gget_A <- function(X, y, G, index, T0, beta0, coef0, n, p, N, weights, B00) {
    .Call(`_BeSS_gget_A`, X, y, G, index, T0, beta0, coef0, n, p, N, weights, B00)
}

bess_lm <- function(X, y, T0, max_steps, beta, weights, normal = TRUE) {
    .Call(`_BeSS_bess_lm`, X, y, T0, max_steps, beta, weights, normal)
}

bess_lms <- function(X, y, T_list, max_steps, beta0, weights, warm_start = FALSE, normal = TRUE) {
    .Call(`_BeSS_bess_lms`, X, y, T_list, max_steps, beta0, weights, warm_start, normal)
}

bess_lm_gs <- function(X, y, s_min, s_max, K_max, max_steps, epsilon, beta0, weights, warm_start = FALSE, normal = TRUE) {
    .Call(`_BeSS_bess_lm_gs`, X, y, s_min, s_max, K_max, max_steps, epsilon, beta0, weights, warm_start, normal)
}

gbess_lm <- function(X, y, G, index, orderGi, PhiG, invPhiG, T0, max_steps, beta0, weights, n, p, N, normal = TRUE) {
    .Call(`_BeSS_gbess_lm`, X, y, G, index, orderGi, PhiG, invPhiG, T0, max_steps, beta0, weights, n, p, N, normal)
}

gbess_lms <- function(X, y, G, index, orderGi, PhiG, invPhiG, T_list, max_steps, beta0, weights, n, p, N, warm_start = FALSE, normal = TRUE) {
    .Call(`_BeSS_gbess_lms`, X, y, G, index, orderGi, PhiG, invPhiG, T_list, max_steps, beta0, weights, n, p, N, warm_start, normal)
}

Normalize2 <- function(X, weights) {
    .Call(`_BeSS_Normalize2`, X, weights)
}

EigenR <- function(X) {
    .Call(`_BeSS_EigenR`, X)
}

